### ISSUE TITLE
FirebaseApp has not been initialized properly.

### ISSUE THREAD

**Issue by DreamyPhobic** [opendatakit/skunkworks-bat#19]
W/System.err: java.io.FileNotFoundException:/storage/emulated/0/opendatakit/default/config/assets/google-services.json (No such file or directory)
W/System.err:     at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:200)
        at java.io.FileInputStream.<init>(FileInputStream.java:150)
        at org.odk.odknotifications.Activities.MainActivity.loadJSONFromAsset(MainActivity.java:134)
        at org.odk.odknotifications.Activities.MainActivity.readConfigFile(MainActivity.java:457)
        at org.odk.odknotifications.Activities.MainActivity.requestStoragePermission(MainActivity.java:494)
        at org.odk.odknotifications.Activities.MainActivity.onCreate(MainActivity.java:97)

**Comment by linl33** [comment]
It couldn't find `google-services.json` because the server you used wasn't configured by `skunkworks-parrot`. 

@DreamyPhobic Do you want to work on this issue? Maybe provide an error dialog when the necessary file is missing.

**Comment by DreamyPhobic** [comment]
Yeah sure...

**Comment by DreamyPhobic** [comment]
I was trying hard to setup skunkwork-parrot but it's prerequisites contains almost all things i am ever known to. :smile:
